import React,{useEffect} from 'react';
import { Col, Container, Row } from 'react-bootstrap';
import './Footer-item.css';
function VendorAgreement() {
    useEffect(()=>{
        window.scrollTo({
            top: 0,
        });
      },[]);
    return (
        <Container fluid>
        <div className='card privacy'>
            <div className='div-privacy'>
                <h3 className='head-txt'>Seller Agreement</h3>
                <p className='p-txt'>
                    Hoolo.live makes available an interactive streaming e-commerce platform the "Hoolo.live Platform that facilitates the sales of fashion and other good s and merchandise and connects merchants like you with consumers. A private limited company incorporated in Bangladesh under the 
                    Respective companies Act 1994,having office at 476/C, Malibagh DIT, 1219<br/>
                    AND<br/>
                    Hoolo.live-A company, registered under the laws of the Peoples Republic of Bangladesh. Hoolo Technologies Limited and Seller are hereinafter referred to collectively as the “Parties” and individually as a “Party” This document is an electronic record in terms of Information Technology and Communication Act 2006 and the amended provisions pertaining to Information Technology and Communication Act of 2006. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
                <h5 className='head-txt'>AGREEMENT </h5>
                <div className='p-txt'>
                This TOS sets out the general terms and conditions on which Hoolo.live offers you access to and use of our websites, platform, applications, and services, including core and supplemental services (collectively, the "Service s"). Use of our mobile application will also be subject to the Mobile Application EULA and some Services will be subject to Supplemental Terms (as defined below) aspublished on our website or made known to you. The "Agreement" means these TOS, the Supplemental Terms applicable to your use of applicable Services, and the Mobile Application EULA with respect to such mobile application. Access and use of our Services are also subject to y our compliance with Hoolo.livepolicies and procedure s on our website or otherwise provided to you.

                <br/><br/>Any individual purporting to represent a Merchant entity represents and warrants that it is authorized to enter into the Agreement on behalf of the Merchant entity it identifies and form a legally binding agreement pursuant to the Agreement.

                <br/><br/>THIS AGREEMENT CREATES A BINDING LEGAL AGREE MENT BETWEEN MERCHANT AND HOOLO.LIVE. PLEASE READ THIS AGREEMENT CAREFULLY.
                <ul>
                    <h6>
                    Nature of the Services.
                    </h6>
                    <li>Overview. The Services are designed to facilitate Merchant and its authorized employees, agents, contractors and representatives (collectively, "Agents") in marketing, promoting, selling and distributing Merchant's goods and merchandise (the "Goods") to end consumers ("Consumers"), subject to the other provisions of this TOS. The Services also are designed to facilitate the hosting of live streaming show(s) ("Live Shows") created by Merchant or independent influencers using our Platform ("Influencers") where Consumers can view, order, and pay for Goods. The Services may also permit Merchant to post, create, upload, store, broadcast and/or transmit via the Hoolo.live Platform certain information or other content (which may include user credentials for Agents, logos, trademarks, data, texts, messages, voice recordings, photo s, video or other materials or content) ("Merchant Materials"). In connection with the Services, Hoolo.live may u se third party payment processing companies to collect. payment from Consumers.
                    </li>
                    <li>Core Services. All Merchant may access and use the core Services made available by us as described on Hoolo.live Platform and related documentation, subject to the provisions of this TOS</li>
                    <li>Ancillary and Supplemental Non-Core Services. Merchant may also elect to receive certain non-core Services offered by Hoolo.live, which may be subject to additional terms and fees ("Supplemental Terms"). Such Supplemental Terms will either be listed in this Agreement or will be presented to Merchant when Merchant signs up to use such Services. Using or registering to use, such non -core Services constitute your agreement to be bound to the Supplemental Terms and pay any addition fees relating to such Services. If these TOS are inconsistent with such Supplemental Terms, the Supplemental Terms shall control with respect to such supplemental Services. Supplemental Services may include Services relating to 
                    (i) the shipping and delivery of Goods, (ii) hosting of Live shows by us or a third party selected through our Platform (including an Influencer), or (iii) other Services identified as such by us. We may add new supplemental Services or discontinue offering any supplemental Services, in whole or in part, at any time unless expressly agreed otherwise in the Agreement.
                    </li>
                    <li>Shipment and Delivery. Unless we expressly agree to ship Goods for you through supplemental Services, Goods will be shipped by Merchant through transportation and shipping carriers of your choice. In no event is Hoolo.liveresponsible for the acts or omissions of any carriers, including any loss or damage to Goods. As between the parties, Merchant is responsible for all risk of loss or damage relating to the Goods and will re-process and re-fulfill orders and process and accept returns or exchanges, as applicable. Merchant shall bear all shipping costs, provided, however, that Merchant may elect to pass such shipping costs on to Consumers in its sole discretion.
                    </li>
                    <li>Services and Returns. Merchant will be responsible for authorizing the return of Goods from a Consumer in exchange for a full or partial refund or exchange, as determined by Merchant. In the case that BANGLADESH. Customs or any Bangladeshi or non-Bangladeshi. authority requests information, documents and/or other evidence regarding any exportation or importation of any Goods or other compliance matters or such information is required for legal reasons or to address, mitigate, or determine taxes or duties on return s or other transactions, the parties will work in good faith, in a timely manner, to provide said evidence to said agencies. Any refunded duties and taxes in relation to a return which were paid at the time of purchase by the Consumer will be refunded to Consumers using the means of payment utilized for the initial collection of such duties and taxes. Merchant shall bear all shipping costs, provided, however, that Merchant may elect to pass such shipping costs on to Consumers in its sole discretion.
                    </li>
                    <li>Prohibited Goods. Merchant will ensure that it does not promote, market, offer, sell, or ship any Goods-
                        <ul>
                        <li>not legally allowed to be sold, including regulated or prohibit ed drugs, weapons, or other Goods subject to import/export controllicenses or restrictions,
                        </li>
                        <li>made from any type of endangered wild plant or animal that is in the list of species protected by the Convention on International Trade in Endangered Species, that fall into one or more of the wildlife(conservation and security act,2012)
                        </li>
                        <li>that are classified as fish or wildlife as determined by Bangladesh. Fish & Wildlife department or other legal authority, 
                        </li>
                        <li>that are perishable according to any Bangladesh or other applicable transportation authority.
                        </li>
                        <li>incorrectly labelled or packaged or subject to false or illegal claims, or 
                        </li>
                        <li>that infringe or misappropriate the rights of a third party or are subject to an injunction or court order prohibiting the sale or shipment thereof (collectively, Prohibited Goods"). Hoolo.live will have the right to ref use any Services with respect to any Prohibited Goods, and Merchant will indemnify and hold harmless Hoolo.live for any damages, losses and liabilities that Hoolo.live may suffer arising from or in connection with such prohibited Goods.
                        </li></ul>
                    </li>
                    <li>Cloud Services and Third-Party Services. Without limitation of the disclaimers and limitations of liability set for the in this Agreement, Merchant acknowledges and agree as follows: 
                        <ul>
                        <li>we provide the Services using cloud computing services of one or more third party cloud providers (collectively, the "Cloud Providers"); and 
                        </li>
                        <li>we shall not be responsible or liable for any act, omission or failure of any Cloud Provider. The Services may depend upon, interaction with or enable access to third parties' information, other content, services or websites ("Third Party Services"), which may in each case be accompanied by separate terms of use. Use of each Third-Party Services may require that Merchant accepts additional terms of use. Merchant must comply with the applicable terms of use when using the Third-party Services and the Services. Hoolo.live does not endorse, and hereby disclaims all lability or responsibility to Merchant or any other person for, any third-party Services.
                        </li>
                        </ul>
                    </li>
                    <li>social media. From time-to-time, we may offer functionality on the Services permitting Merchant to connect the Services to Merchant's Facebook, Twitter, Instagram or other social media accounts ("Social Media Accounts"). If merchant chooses to connect Merchant's Hoolo.live account with any Social Media Accounts, Merchant will be able to take advantage of various social features Hoolo.live may already have or will be creating, as part of the Services, as well as features available on such Social Media Accounts. These features will generally be designed to share information with others. For example, Merchant's friends and others who have access to view information about Merchant on Facebook may be able to see (on Facebook and on the Services) that Merchant are a user of the Services, and other information about Merchant's use of the Services. Merchant may also be able to see similar information about Merchant's Facebook friends who are users of the Services. Please pay careful attention to Merchant's relevant Social Media Account settings in Merchant's Services account as well as Merch ants privacy settings in Merchant's Social Media Accounts which will impact this feature, when available, and may give Merchant some control over the information that  is shared and with whom it is shared.
                    <br/><br/>BY CONNECTING MERCHANT'S SERVICES ACCOUNT TO ANY SOCIAL MEDIA ACCOUNT, MERCHANT ACKNOWLEDGES AND AGREE THAT MERCHANT IS CONSENTING TO THE CONTINUOUS RELEASE OF INFORMATION ABOUT MERCHANT TO OTHERS, INCLUDING TO THE RELEVANT SOCIAL MEDIA ACCOUNT (IN ACCORDANCE WITH MERCHANT'S PRIVACY SETTINGS ON SUCH SOCIAL MEDIA ACCOUNT AND MERCHANT'S SETTING S ON THE SERVICES). IF MERCHANT DOESNOT WANT INFORMATION ABOUT MERCHANT TO BE SHARED IN THIS MANNER, PLEASE CHANGE MERCHANT'S SETTINGS APPROPRIATELY. 
                    <br/><br/>Hoolo.live and social media sites are continually making changes and improvements to this feature, and therefore the available features and information that are shared may change from time to time. these changes may take place without notice to Merchant and may not be described in this Agreement.
                    </li>
                    <h6>Use of Hoolo.livePlatform.
                    </h6>
                    <li>Merchants' Responsibilities. As between the parties, Merchant (not Hoolo.live) is solely responsible for 
                        <ul>
                        <li>Merchant Materials, including the accuracy and completeness</li>
                        <li>The Goods, including any loss, damage, injury, or death caused by the Goods, and Goods returns, repair, replacement, warranty obligations or recalls
                        </li>
                        <li>obtaining and documenting consents from Consumers, Influencers, and other third parties required for Hoolo.live (and its third-partycontractors or processors) to perform its obligations and receive, process, transmit, and display information and data as contemplated under this Agreement; and
                        </li>
                        <li>its business practices and use of our Platform as contemplated under the Agreement. Merchant will use commercially reasonable efforts to prevent fraudulent, unauthorized or illegal access to or use of, and loss or damage to, the Hoolo.live Platform to the extent within Merchant's control, and notify Hoolo.live promptly of any such event or circumstance. Merchant will also use the Hoolo.live Platform only in accordance with this Agreement and applicable laws and regulations for its business, and notify Hoolo.live promptly of any know n or suspected use in violation thereof.
                        </li>
                        </ul>
                    </li>
                    <li>Registration. In order to use certain Services, Merchant may be required to provide us with its and its authorized Agents' contact and other information including full legal name, email address, mailing address, phone number, social media handles, or other information and create a password and register with us. We may also request additional information. Merchant represents and warrants that it will provide us with accurate, current and complete registration information. Merchant is responsible for keeping all such credentials and passwords issued to its Agents confidential and secure.
                    </li>
                    <li>Acceptable User Conduct.</li>
                    <li>Merchant and its Agents must comply with any rules and policies about use of the Services that we publish from time to time. Merchant shall be responsible for its Agents' acts or omissions. Subject to the terms and conditions herein, Merchant is permitted to use the Services solely for marketing, promoting, selling, distributing Merch ant's Goods (the "Specified Purpose").
                    </li>
                    <li>Merchant and its Agents must not:

                    Merchant and its Agents must not: (A) create, upload or transmit any Merchant Materials if it does not have the right to do so; (B) create, upload or transmit Merchant Materials or use the Services in any way that would violate any law or the rights of any person; (C) impersonate any person or entity, or forge or manipulate headers to disguise the origin of any of Merchant Materials; (D) except as otherwise expressly permitted by this Agreement, harvest or otherwise collect information about others from the Services; (E) take any action that imposes or may impose an unreasonable or disproportionately large load on the Services or its infrastructure, or bypass any measures we may use to prevent or restrict access to any portion of the Services (or other accounts, networks or serv ices connected thereto); (F) use manual or automated software, devices, or other processes to "crawl," "scrape" or "spider" any of the Services or otherwise to copy, obtain, propagate, distribute or misappropriate any information or other content from the Services, including any of Hoolo.live Property (as defined below); (G) distribute or otherwise make available any information or other content obtained through the Services to any third party, except as expressly permitted herein; (H) otherwise interfere in any manner with the use or operation of the Service s; (1) abuse the Services' chat, comments, ratings or review features or sections; (J) circumvent the Platform or transact directly with a Influencer outside of the Platform in order to avoid Hoolo.live fees; or (K) use the Services in the development, directly or indirectly, of any product, software or service that offers any functionality substantially similar to, or competitive with, the Services.
                    </li>
                    <li>
                    Merchant Materials must not:

                    Merchant Materials must not: (A) be libelous, vulgar, defamatory, threatening, abusive, scandalous, obscene, pornographic or unlawful or encourage a criminal offense; (B) contain material from other copyrighted works without the written consent of the owner of such copyright ed material; (C) infringe any copyright or violate any property rights, rights of privacy or publicity, or any other rights of any third party; or (D) contain any software virus es, malware, spyware or any other code, file or program that is designed to interrupt, destroy or limit the functionality of any computer software, hardware or telecommunications equipment.

                    </li>
                    Free and Economic Terms.
                    <ul>
                        <li>
                        Services Fees. 
                        In consideration for access to and use of the Services, Hoolo.live shall be entitled to 10 % commission on products sold at events hosted by the Merchant or a 20% commission on products sold at events for which Hoolo.live provides a host, and any ancillary costs or expenses Hoolo.live incurs in connection with the transactions relating to this Agreement, including shipping, handling, taxes, duties, import/export, payment processing, chargeback, currency exchange or other similar costs or expenses: in each case as more other similar costs or expenses; in each case, as more thoroughly described in the Platform, as applicable and as then in effect, and subject to change from time to time in the sole discretion of Hoolo.live (collectively "Hoolo.live Total Fees").

                        </li>
                        <li>Deduction from Amounts Collected for the Goods. Hoolo.live may deduct or set-off such Hoolo.live Total Fees from any amounts collected by Hoolo.live from Consumers or for amounts due to Merchant for the Goods</li>
                        <li>Merchant Payment Information. Merchant will provide Merchant's payment information to Hoolo.live, which may be bank account and MFS account, such that Hoolo.live is able to remit payment for Goods less Hoolo.live’s Total Fees. Merchant is responsible for third party payment service fee.
                        </li>
                        <li>Taxes. Hoolo.live fees are net of any applicable Sales Tax. If any Services, or payments for any goods or Services, under this Agreement, are subject to Sales Tax in any jurisdiction, Merchant (or the Consumer) will be responsible for payment of such Sales Tax, and any related penalties or interest and Merchant will indemnify Hoolo.live for any liability or expense Hoolo.live may incur in connection with such Sales Taxes. For purposes of this Agreement, "Sales Tax" shall mean any sales or use, value added, or similar tax or amount, and any other tax or amount measured by sales proceeds or assessed by a governmental or taxing authority in any jurisdiction. Hoolo.live may automatically charge and withhold such taxes or other amounts.
                        </li>
                    </ul>
                    <h6>Hoolo.liveProperty.</h6>
                    <li>Hoolo.live Property. The Services, including all aspects of Hoolo.live Platform (including Hoolo.liveProperty, as defined below), is the property of, and owned by, Hoolo.live or its licensors. All the software, algorithms, functionality, inventions, concepts, text, images, sound, music, videos, marks, logos, compilations, content and technology used to deliver the Services or otherwise embodied in, displayed through, or provided directly or indirectly (e.g., emails or other communications from us to you) via the Services are "Hoolo.live Property". For clarity, any formats, templates, methodologies, rules, algorithms and software used to create Merchant Materials are Hoolo.liveProperty. Except as otherwise expressly permitted by this Agreement, any use, copying, making derivative works, transmitting, posting, linking, deep linking, framing, redistribution, sale, de-compilation, modification, reverse engineering, translation or disassembly of Hoolo.liveProperty is prohibited. Merchant acknowledges that Hoolo.liveProperty has been created, compiled, developed and maintained by us at great expense of time and money such that misappropriation or unauthorized disclosure or use of Hoolo.liveProperty by others for commercial gain would unfairly and irreparably harm us in a manner for which damages would not be an adequate remedy, and Merchant consents to our obtaining injunctive relief to restrain any breach or threatened breach of this Agreement, without any requirement to post bond. Merchant or its Agents may be subject to criminal or civil penalties for violation of this paragraph.
                    </li>
                    <li>Hoolo.live Trademarks. The marks, HOOLO.LIVE is---- “Unlimited Social Shopping” and any associated logos ("Hoolo.live Marks"), are registered or unregistered trademarks or service marks of Hoolo Technologies Ltd.. or its licensors. Merchant shall use the Hoolo.live Marks only in the manner and for purposes authorized by Hoolo.live and shall ensure that all uses include appropriate copyright and trademark notices. Merchant may not use them, or any of our other marks or logos, in any manner, including any use that is likely to cause confusion on or that disparages or discredits us, without our consent. The Services may also feature the trademarks, service marks, and logos of third parties, and each owner retains all rights in such marks. Any use of such marks, or any others displayed on the Services, will inure solely to the benefit of their respective owners. In addition to the license grantedHoolo.live hereby grants to Merchant the non-exclusive, limited right and revocable license to use Hoolo.live Marks for promoting services provided by Hoolo.live subject to Merchant's compliance of this Agreement. Merchant warrants that its use of any Hoolo.live Mark shall conform to Hoolo.live then current trademark and logo guidelines, and other Hoolo.live requirements governing the use of Hoolo.live Marks as notified to Merchants from time to time.
                    </li>
                    <li>License to use Hoolo.liveProperty. Subject to the terms and conditions herein, we grant Merchant the non-exclusive, limited, revocable right to access and use Hulusthul’s Property solely to the extent necessary for Merchant to use the Services for Merchant's own Specified Purpose (as defined above), as permitted by this Agreement. We reserve all other rights. For clarity and without limiting other obligations herein, Merchant shall not distribute or otherwise commercialize Hoolo.liveProperty without permission.
                    </li>
                    <h6>Other Propriety Rights.</h6>
                    <li>Merchant Materials. Merchant retains its rights in Merchant Materials, subject to the rights granted below and our rights in Hoolo.liveProperty. For clarity, Merchant Materials do not include Live Shows, which are subject to Section 5.2 below. Merchant hereby grants and agrees to grant us a worldwide, non-exclusive, perpetual, irrevocable, royalty-free, fully-paid, transferable license, with the right to sublicense through multiple tiers, to copy, ed it, modify, adapt, publish, transmit, distribute, prepare derivative works, perform, display, use, and otherwise exploit in any manner, Merchant Materials in connection with operation and promotion of the Services and any other purposes reasonably related to the Services or our busine ss. To the extent reasonably necessary or appropriate to effect or support the license granted by Merchant above Merchant hereby waives and agrees to waive (or if not waivable, agrees not to assert) any rights of privacy or publicity, or any moral rights or other similar rights, with respect to Merchant Materials. Merchant also hereby grants and agrees to grant Consumers and other users of Hoolo.live Platform a worldwide, non-exclusive, royalty -free license to access, copy and use Merchant Material s which:
                        <ul>
                            <li>Merchant or its Agent transmits to such users via the Hoolo.live Platform or 
                            </li>
                            <li>Merchant or its Agents post within any public forum or similar area of the Services that is available to such users generally, in each case solely for Merchant's Specified Purpose in accordance with the Agreement. In addition to and without limiting any other rights herein (including in the Privacy Policy), Merchant also grant Hoolo.live the rights to: 
                            </li>
                            <li>de-identify Merchant Materials (i.e., to remove Merchant's name and other identifying characteristics, consistent with applicable laws and regulations), 
                            </li>
                            <li>use or disclose de-identified data for any purpose, and 
                            </li>
                            <li>allow us to share de-identified data with third parties. On termination of Merchant's account(s) or this Agreement, we have no obligation to return any Merchant Materials to Merchant, so Merchant should retain copies of Merchant Materials for its own purposes. We reserve the right (but are under no obligation) to investigate any claim that Merchant's Materials or Merchant's use of the Services does not conform to this Agreement. In the event that we deem, in our sole discretion, any Merchant Material to be inconsistent with the terms of this Agreement, Hoolo.live Privacy Policy, or any other rules or policies we may publish from time to time, we may remove such Merchant Materials from the Hoolo.live Platform, including incomplete posts, duplicate posts, or any other Merchant Materials we deem, in our sole discretion, to be misleading or otherwise inappropriate, or terminate or suspend Merchant's account(s).
                            </li>
                        </ul>
                    </li>
                    <li>
                    Live Shows. Live Shows are to be filmed by Merchant and broadcast via the Platform through the Services, unless otherwise specified. Merchant shall obtain all necessary consents, waivers, releases, permits, and other authorizations from all necessary persons and entities, including but limited to: 
                        <ul>
                            <li>all persons who may appear or who se image, likeness or trademarks may appear in the Live Shows, including Influencers or any other third parties selected from the Platform, 
                            </li>
                            <li>all locations where Live shows are filmed, and</li>
                            <li>all Merchants or other entities w hose images or trademarks may appear in the Live Show s, in each case, to the extent necessary or required by applicable law or regulation for Hoolo.live to perform the Services and broadcast the Live Shows as contemplated hereunder and for Merchant to provide Hoolo.live the rights below. As between the parties, Hoolo.live is and will be the sole and exclusive owner of all rights, title, and interest in and to the Live Shows (including all film, photographs, and other recordings, including outtakes and behind-the-scenes footage), including all copyrights and other intellectual property rights therein or thereto. Merchant hereby irrevocably assigns to Hoolo.live all right, title and interest in and to the Live Shows, including all rights in and to any intellectual property rights embodied in Live Shows or developed in the course of the creation of the Live Shows and will cause all applicable individuals and entities to grant or waive any moral or other rights they may have in or to the Live Shows for Hoolo.live to have and exercise the rights contemplated in this Section. Subject to Merchant's compliance to this Agreement, Hoolo.live hereby grants Merchant a non-exclusive, limited and revocable license to download, use, perform and display Live Shows 
                                <ul>
                                    <li>in connection with Services on Hoolo.live Platform, or 
                                    </li>
                                    <li>on third party websites or mobile applications, on the condition that Merchant keeps any trademark, copyright notices, legends or water marks intact.
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li>Feedback. If Merchant or its Agents provide to us (directly or indirectly, and by any means) any comments, feedback, suggestions, ideas, or other submissions related to the Services (collectively "Feedback"), the Feedback will be the sole property of Hoolo.live. We will be entitled to use, reproduce, disclose, publish, distribute, and otherwise exploit in any manner, all Feedback, without restriction and free of charge. We shall have no obligation t o maintain any Feedback in confidence, or to respond to any Feedback.
                    </li>
                    <li>Publicity. Hoolo.live shall have the right to use Merchant's name and logo on Merchant lists published on Platform and in marketing materials. Hoolo.live may announce the relationship here under in a press release provided that Hoolo.live obtains Merchant's prior approval of the wording of the release (not unreasonably withheld).
                    </li>
                    <li>Term; Termination; Account Suspension.</li>
                    <li>Merchant or any of its Agent has breached or defaulted under any t erm of this Agreement;
                    </li>
                    <li>Merchant's use of our Services may pose significant risks to Hoolo.livereputation or systems or other users of our Platform; or 
                    </li>
                    <li>Merchant or any of its Agents' use of our Services violates applicable laws or regulations. We may also terminate, in whole or in part, atour convenience, and will endeavor to providethirty (30) days' notice for any such termination.
                    </li>
                    <li>Following any termination or expiration, Merchant must: 
                        <ul>
                            <li>immediately discontinue all access and use of all Hoolo.live' Property, 
                            </li>
                            <li>immediately discontinue all access and use of all Hoolo.live' Property
                            </li>
                            <li>promptly return to Hoolo.live (or delete) any copies of Hoolo.live' Property then in Merchant's possession or control;
                            </li>
                            <li>cease identifying Shop Shops as its e-commerce provider, and </li>
                            <li> give written notice to Shop Shops certifying the foregoing. Merchant will remain liable for all payments due to Hoolo.live with respect to the period ending on the date of termination or expiration. Upon any termination or expiration, the balance of all remaining Hoolo.live Total Fees will be du e and payable immediately plus any other amounts owed. The provisions of the Agreement that are required or intended to survive (including payment, indemnity, limitation of liability, intellectual property, confidentiality etc.) to give each party the rights and benefits reasonably contemplated will survive any termination or expiration.
                            </li>
                        </ul>
                    </li>
                    <li>Representations and Warranties. Merchant represents and warrants that:
                    </li>
                    <li>it is in good standing, has all the licenses, regulatory approvals, permits and powers legally required to conduct its business, and has the power, authority and legal right to execute and perform this Agreement.

                    </li>
                    <li>the execution or consummation of this Agreement will not breach any obligations of Merchant under any contract to which it is a party or violate any applicable laws.
                    </li>
                    <li>it has the right sell and distribute the Goods as contemplated under these TOS, and all Goods are and will: 
                    </li>
                    <li>be free from any defects in workmanship, material, and design; 
                    </li>
                    <li>conform to applicable specifications and other requirements communicated to Hoolo.live or Consumers;

                    </li>
                    <li>be fit for their intended purpose and operate as intended; 
                    </li>
                    <li>be merchantable;
                    </li>
                    <li>be conveyed with goo d title, free and clear of all liens, security interests, or ot her encumbrances; and
                    </li>
                    <li>be original, legitimate and genuine quality products, which are procured from legitimate channels in accordance with all legal requirements. Th e Goods and any related packaging, conform fully to any applicable laws, rules and regulations (including intellectual property laws and applicable consumer goods certifications in the country or other jurisdiction to which such Goods are shipped). Merchant will honor and pass-through to Hoolo.live, if necessary, all warranties relating to the Goods so Hoolo.live may provide the same to Consumers;
                    </li>
                    <li>it owns all proprietary rights in Merchant Materials or, with respect to any of Merchant Materials it does not own, that it has the full authority and right to create, upload, store and/or transmit Merchant Materials, and to grant the licenses and rights it granted in this Agreement, and that Merchant's creation, uploading, storage and/or transmission of Merchant Materials, and the exercise by us and Consumers of the licenses and rights granted by Merchant herein, shall not infringe any third party intellectual property or proprietary rights, nor violate any rights of privacy or publicity, nor be defamatory, libelous, vulgar, profane or obscene, nor violate any law or other right, privilege or interest of any third party.
                    </li>
                    <li>Warranty Disclaimers.
                        <ul>
                            <li>
                            General. THE SERVICES ARE PROVIDED "AS IS", WIT H ALL FAULTS. WE EXPRESSLY DISCLAIM ANY AND A LL WARRANTIES, WHETHER EXPRESS OR IMPLIED, IN CLUDING: 
                                <ul>
                                    <li>ALL WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NONIN FRINGEMENT, AND ANY AND ALL WARRANTIES ARISIN G FROM THE COURSE OF DEALING OR USAGE OF TR ADE; 
                                    </li>
                                    <li>THAT THE SERVICES OR HOOLO.LIVEPROPE RTY WILL MEET MERCHANT'S REQUIREMENTS, WILL ALWAYS BE AVAILABLE, ACCESSIBLE, UNINTERRUPTE D, TIMELY, SECURE OR OPERATE WITHOUT ERROR; AND
                                    </li>
                                    <li>AS TO THE ACCURACY OR RELIABILITY OF AN Y INFORMATION OBTAINED FROM THE SERVICES OR HOOLO.LIVEPROPERTY.
                                    </li>
                                </ul>
                            </li>
                            <li>Third Party Activities. HOOLO.LIVE MAKES NO REPR ESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF CONSUMERS, INFLUENCERS AND OTHER USERS O F OUR SERVICES. MERCHANT AGREES TO USE ITS O WN BUSINESS JUDGEMENT IN ALL INTERACTIONS OR TRANSACTIONS WITH OTHER USERS OF THE SERVICE S OR CONSUMERS. We make no representation, warranty or endorsement regarding any third parties on our Platform, or the authenticity or validity of any materials dis played in connection with the Services. By using the Ser vices, Merchant agrees that the sole remedy for any da mage or harm inflicted by a third party using the Platform (including Consumers and Influencers) will be limited to claims against such third party, and that Merchant will not seek monetary damages or any other remedy from u s in connection with such events. Merchant agrees that we are not responsible for any use or disclosure of Merchant Materials by other users of the Platform or any third party who gains access to it through the Services (which may include unintended activities by third parties, such as by hackers). HOOLO.LIVE HEREBY DISCLAIMS AL L LIABILITY FOR ANY ACT OR OMISSION OF ANY USER S OF THE SERVICES OR THIRD PARTIES.
                            </li>
                            <li>System Unavailability & Errors. There may be times when the Hoolo.live Platform is unavailable due to technical errors or network outages or for maintenance and support activities. Our Platform may contain typographical mistakes, inaccuracies, or omissions and some information may not be complete or current. We expressly reserve the right to correct any errors, inaccuracies, or omissions and to change or update information at any time without prior notice. We do not make any representation or warranty concerning errors, omissions, delays, or defects in our Services or any information supplied to Merchant via the Hoolo.live Platform, or that files available through the Hoolo.live Platform are free of viruses, worms, trojan horses, or other code that includes or manifests contaminating or destructive characteristics.
                            </li>
                        </ul>
                    </li>
                    <li>Limitations of Liability. UNDER NO CIRCUMSTANCES WILL MERCHANT BE ENTITLED TO RECOVER FROM US ANY INCIDENTAL, CONSEQUENTIAL, INDIRECT, PUNITIVE OR SPECIAL DAMAGES (INCLUDING DAMAGES F OR LOSS OF BUSINESS, LOSS OF REVENUE, LOSS OF DATA, OR LOSS OF USE), WHETHER BASED ON CONT RACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWI SE ARISING FROM OR RELATING TO THIS AGREEMENT THE SERVICES, HOOLO.LIVEPLATFORM OR SHOPS HOPS' PROPERTY, EVEN IF WE HAVE BEEN INFORME D OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. TO THE EXTENT PERMITTED BY APP LICABLE LAW, HOOLO.LIVEMAXIMUM AGGREGATE L IABILITY TO MERCHANT FOR ANY DAMAGES ARISING FROM OR RELATING TO THIS AGREEMENT, THE SERVI CES OR HOOLO.LIVEPROPERTY, WHETHER BASED O N CONTRACT, TORT (INCLUDING NEGLIGENCE), OR O THERWISE, SHALL BE LIMITED TO HOOLO.LIVE TOTA L FEES FOR THE THREE (3) MONTH PRIOR TO THE LA ST CLAIM (OR, IF MERCHANT IS A NON-FEE PAYINGUSER, TEN DOLLARS ($10)). SOME JURISDICTIONS DO N OT ALLOW THE LIMITATION OR EXCLUSION OF WARD ANTIES OR OF LIABILITY FOR CERTAIN TYPES OF DAM AGES, SO SOME OF THE ABOVE LIMITATIONS OR EXC LUSIONS MAY NOT APPLY TO MERCHANT.
                    </li>
                    <li>Indemnity. Merchant will indemnify us, and our licensors, affiliates, providers and agents, against any and all claims, actions, proceedings, suits, liabilities, losses, da mages, costs, expenses and attorneys' fees arising out of or related to 
                        <ul>
                            <li>the Goods, including product liability; 
                            </li>
                            <li>Hoolo.live', Consumers, Influencers or other person' s or entity's purchase, use, or possession of the Goods, including any loss, damage to, or destruction of property and/or death or injury to persons;
                            </li>
                            <li>any claim that the Merchant Materials, Live Shows, or any sale, purchase, use or possession of the Goods, infringes or misappropriates the intellectual property rights of any third party or violates applicable laws or regulations; 
                            </li>
                            <li>Merchant's negligence, fraudulent or willful misconduct
                            </li>
                            <li>Merchant 's breach of this Agreement; or 
                            </li>
                            <li>Merchant's use of the Services</li>
                        </ul>
                        We reserve the right to assume the sole control of the defense and settlement of any claim, action, suit or proceeding for which Merchant is obliged to indemnify us. Merchant will cooperate with us with respect to such defense and settlement. Without limitation of the foregoing, if we receive a subpoena or similar requirement to disclose Merchant Materials issued by any court or government al authority, and we are not a party to the proceeding in question, Merchant will reimburse us for our reasonable costs and expenses of complying with such subpoena, including time spent by our personnel and our attorneys at time and materials rates.

                    </li>
                    <li>Digital Security Act 2018. We comply with the provisions of the Digital Security Copyright Act 2018 applicable to internet service providers. If Merchant have any complaints or objections to material hosted by the Merchant may contact our designated Agent at the following address:
                    <br/>Any notice alleging that materials hosted by or distribute d through the Services infringe intellectual property right s must include the following information:
                        <ul>
                            <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other right being infringed
                            </li>
                            <li>a description of the copyrighted work or other intellectual property that Merchant claim has been infringed; 
                            </li>
                            <li>a description of the material that Merchant claim is infringing and where it is located on the Services; 
                            </li>
                            <li>Merchants address, telephone number, and email address;
                            </li>
                            <li>a statement by Merchant that Merchant has a good faith belief that the use of the materials on the Services of which Merchant are complaining is not authorized by the copyright owner, its agent, or the law; and 
                            </li>
                            <li>a statement by Merchant that the above information in Merchant's notice is accurate and that, under penalty of perjury, Merchant is the copyright or intellectual property owner or authorized to act on the copyright or intellectualproperty owner's behalf.
                            </li>
                        </ul>
                        Counter Notices<br/>
                        If merchant has posted to the Services has been removed or disabled, you may file a counter notice pursuant to 17 BANGLADESH.C. §512 (g). To be effective, the counter notice must be a written communication sent to the designated agent address listed above that includes the following:
                            <ul>
                                <li>a physical or electronic signature of the sub scriber;
                                </li>
                                <li>identification of the material that has been re moved or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;
                                </li>
                                <li>a statement under penalty of perjury that Merchant have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be remove d or disabled; and
                                </li>
                                <li>your name, address, and telephone number, and a statement that Merchant consent to the jurisdiction of Federal District Court for the judicial district in which the address is located or, if Merchant's address is outside of the United States, for any judicial district in which Hoolo.live may be found, and that Merchant will accept Services of process from the person who provided notification under subsection 17 BANGLADESH.C. §512 (c)(1)( C) or an agent of such person.
                                </li>
                            </ul>
                            Repeat Infringers<br/>

                            It is our policy to terminate in appropriate circumstances the accounts of users that are repeat infringers or repeatedly violate this Agreement.
                            
                    </li>
                    <li>Modification of Services and Agreement. We reserve the right to modify the Services at any time, without notice to Merchant. We may also from time to time amend or restate this Agreement prospectively. If such amendment or restatement is material or if required by law, we will endeavor to notify Merchant or its Agents by email or by posting the change on the Service platform and/or applicable mobile application. Merchant agrees that Merchant’s continued use of the services constitutes merchant’s agreement to the amended or restated agreement. Merchant must terminate Merchant's account and cease using the Services. Except as set forth above, this Agreement may be amended or modified only by an express writing signed by an authorized representative of Hoolo.live.
                    </li>
                    <li>Governing Law. Merchant andwe each agree that all disputes or other matters arising from or relating to this Agreement, or the use or operation of the Services, will be governed by the substantive laws of the State of New York, BANGLADESH.A., without regard to its or any other jurisdiction n's conflicts of laws principles that would apply another law. Any action or proceeding by Merchant relating to an y claim arising from or relating to the Services or this Ag reement must commence within the shorter of the applic able statute of limitations or one year after the cause of action has accrued. The United Nations Convention for the International Sale of Goods is hereby disclaimed.
                    </li>
                    <li>Arbitration.

                    </li>
                    <li>Force Majeure. In no event will we be liable for any failure to comply with this Agreement to the extent that such failure arises from factors outside our reasonable control. Without limitation of the foregoing, in the absence of our gross negligence or willful misconduct we will not be liable for any damages arising from the acts of hackers or similar bad actors interfering with the Services or using or disclosing any of Merchant Materials.
                    </li>
                    <li>Compliance with Laws. Merchant will comply with allActs,restriction,regulation,bye-laws,prohibition or measures of any kind on the part of governmental,parliamentary or local authorityapplicable to Merchant's Goods and activities under or in connection with this Agreement.
                    </li>
                    <li>Geography & Language. We are based in Bangladesh.Bangla version shall govern. We make no claims that the Services or any of its content is accessible or appropriate outside of the Bangladesh. Access to the Services may not be legal by certain persons or in certain countries. If Merchant or its Agents access the Services from outside the Bangladesh, Merchant does so on its own initiative and are responsible for compliance with local laws. This Agreement has been prepared in English.
                    </li>
                    <li>Relationship of the Parties. The relationship between the parties is that of independent contractors. Nothing contained in this Agreement shall be construed as creating any agency, partnership, joint venture or other form of joint enterprise or employment relationship between the parties, and neither party shall have authority to contract for or bind the other party in any manner whatsoever.
                    </li>
                    <li>
                    Miscellaneous Provisions. No delay or omission by us in exercising any of our rights occurring upon any noncompliance or default by Merchant with respect any of the terms and conditions of this Agreement will impair any such right or be construed to be a waiver thereof, and a waiver by us of any of the covenants, conditions or agreements to be performed by Merchant will not be construed to be a waiver of any succeeding breach thereof or of any other covenant, condition or agreement herein. No waiver will be binding on us unless made in an express writing signed by us. If any provision of this Agreement is found by a court of competent jurisdiction to be invalid or unenforceable, then this Agreement will remain in full force and effect and will be reformed to be valid and enforceable while reflecting the intent of the parties to the greatest extent permitted by law. Except as otherwise expressly provided herein, this Agreement sets forth the entire agreement between us regarding its subject matter, and supersedes all prior promises, agreements or re presentations, whether written or oral, regarding such subjectmatter. This Agreement and Merchant's rights and obligations hereunder are not assignable, or otherwise transferable or delegable, by Merchant to any third party without our prior written consent in our sole discretion. Any purported assignment, transfer or delegation without such consent will be null and void. We may assign or otherwise transfer or delegate this Agreement (including any rights or obligations hereunder), including to any purchaser of our business, from time-to-time in our sole discretion. This Agreement will be binding upon and inure to the benefit of the parties' successors and permitted assigns. This Agreement may be executed electronically, and Merchant's electronic assent or use of the Services shall constitute execution of this Agreement. Merchant agrees that the electronic text of this Agreement constitute a writing and its assent to the terms and conditions hereof constitutes a "signing" for all purposes. As used herein and unless the intent is expressly otherwise in aspecific instance, the terms "include," "includes" or "including" shall not be limiting and "or" shall not be exclusive. Any section headings herein are for convenience only and do not form a part of, and will not be used in the interpretation of, the substantive provisions of this Agreement. Merchant agrees that email to Merchant's email address on record will constitute formal notice under this Agreement. There shall be no third-party beneficiaries to this Agreement.
                    </li>
                    <li>Supplemental Terms - Logistics and Support
                    <br/><br/>Hoolo.live may offer logistics and support services as an optional supplement Service as described in our then current documentation for such supplemental services for the amounts described on our Platform. If Merchant elects to use this supplemental Service as and if offered by Hoolo.live, then the following Supplemental Terms apply solely with respect to such supplemental Services:
                    <br/><br/>1. Shipment, Delivery Requirements and Risk of Loss. Merchant shall deliver the Goods to the shipping location(s) specified in writing by Hoolo.live (the "Fulfillment Centers"). Merchant shall timely provide shipment tracking in formation to Hoolo.live for all shipped Goods pursuant to Hoolo.livepolicies and documentation. Merchant bears all risk of loss or damage to the Goods until delivery of the Goods to the shipping location specified by Consumer, is solely responsible for procuring insurance relati ng to such Goods, and hereby waives (and will cause its insurers to waive) any right of subrogation or to seek re course against Hoolo.live or its affiliates, warehousers, contractors or insurers in connection therewith. Merchant is solely responsible for shipping costs for shipping of the Goods from Merchant to Fulfillment Centers and from Fulfillment Centers to Consumers as set forth on the Platform and from time to time in Hoolo.livepolicies and documentation.
                    <br/><br/>
                    2. Acceptance of Goods. If Hoolo.live determines, in its sole discretion, that Goods delivered under this Agreement are damaged, defective, or non-conforming, or were delivered to Hoolo.liveas a result of Merchant's error, Hoolo.live may: 
                    <ul>
                        <li>reject and return such Goods for a refund plus reimbursement by Merchant of any inspection, testing, shipping, handling, and transportation costs or expenses incurred by Hoolo.live; or 
                        </li>
                        <li>require prompt correction or replacement of such Goods.</li>
                    </ul>
                    <br/><br/>
                    3. Changes to Orders. Hoolo.live may, in its sole discretion, cancel or modify the details of an order (including without limitation the types and quantities of Goods specified therein) at any time prior to shipment by Merchant of such Goods.
                    <br/><br/>
                    4. Inventory. If Hoolo.live has any excess or remaining inventory of Goods in the event Hoolo.live purchases inventory in advance of an event or show, then Hoolo.livemay return such inventory to Merchant for a full refund of    any amounts paid for such Goods plus reimbursement by Merchant to Hoolo.live of any reasonable shipping, handling, and transportation costs or expenses incurred by Hoolo.live, or Hoolo.live may sell and liquidate such inventory and use the proceeds to offset any amount s owed by Merchant to Hoolo.live.
                    <br/><br/>
                    Supplemental Terms - Live Shows Hosted by Influence
                    <br/><br/>
                    Hoolo.live may offer Merchants the ability to identify and engage an independent Influencer as an optional supplement Services for the amounts described on our Platform. If Merchant elects to use theses supplemental Services as and if offered by Hoolo.live, then the following Supplemental Terms apply solely with respect to such supplemental Services:
                    <br/><br/>1. Live Shows will be filmed by a third-party Influencer who is independent of Hoolo.live. Merchant is responsible for its selection of each Influencer.

                    <br/><br/>2. Merchant will be responsible for preparing Merchant's store and Goods for the filming in cooperation with the Influencer, except as otherwise agreed in writing

                    <br/><br/>3. Merchant shall obtain all necessary consents, waivers, releases and other authorizations for the Live Shows.

                    <br/><br/>4. Hoolo.live will have no responsibility or liability for a ny personal injury, death, or property damage arising at Merchant's store or designated filming location for any Live Shows.

                    <br/><br/>5. Hoolo.live will use reasonable efforts to facilitate resolution of any issues or disputes between Influencers and Merchant and may (but is not obligated) to withhold payment or transfer of funds to Influencer or Merchant pending resolution of such issue or dispute or deposit such funds in an escrow account with a reputable bank, subject to Influencer's and Merchant's settlement agreement relating thereto or court order.

                    </li>
                    
                </ul>
                
                </div>
            </div>
        </div>

        </Container>
        );
    }
    
export default VendorAgreement;